version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: npm test
    env_file:
      - .env

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm test
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  db_data:
